// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ams.data.Context;

#nullable disable

namespace ams.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240722192405_ams_mig_v2")]
    partial class ams_mig_v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ams.entity.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("bit");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            AccountName = "ABC A.Ş",
                            CreateTime = new DateTime(2024, 7, 22, 22, 24, 4, 932, DateTimeKind.Local).AddTicks(5161),
                            CreateUser = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            Domain = "abc.com",
                            IsActive = true,
                            IsDeleted = false,
                            IsTrial = true
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.AdxMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icons")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Urls")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AdxMenus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2b3d904-401c-431f-9845-7fa2652d87fc"),
                            CreateTime = new DateTime(2024, 7, 22, 22, 24, 4, 932, DateTimeKind.Local).AddTicks(5965),
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Pano",
                            Urls = "/"
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4033eef-ba92-4a1f-9ecb-1eee6996214a"),
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ApartmentName = "Huzur APT",
                            CreateTime = new DateTime(2024, 7, 22, 22, 24, 4, 932, DateTimeKind.Local).AddTicks(6508),
                            CreateUser = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("16f885ff-6897-4d08-afa6-0640c40d2a05"),
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ApartmentName = "Sevinç APT",
                            CreateTime = new DateTime(2024, 7, 22, 22, 24, 4, 932, DateTimeKind.Local).AddTicks(6513),
                            CreateUser = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("d2977402-d13f-423f-bc0f-e639e4a610bb"),
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ApartmentName = "Güvenç APT",
                            CreateTime = new DateTime(2024, 7, 22, 22, 24, 4, 932, DateTimeKind.Local).AddTicks(6516),
                            CreateUser = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4271dd20-390a-46ce-b67d-59678a720270"),
                            ConcurrencyStamp = "1ec970f4-0921-4b96-950b-07ce4800bf17",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("4438dff4-28d6-46c1-90eb-f6b2a233d97e"),
                            ConcurrencyStamp = "bd698e0d-e0d5-4fe3-b3f3-893aef20da07",
                            Name = "agent",
                            NormalizedName = "AGENT"
                        },
                        new
                        {
                            Id = new Guid("051004f1-a383-4746-a722-3b051d12aaea"),
                            ConcurrencyStamp = "3120fc2a-41c0-4429-ab6e-373a7adad692",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("ams.entity.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("ModifiedUser");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            AccessFailedCount = 0,
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ConcurrencyStamp = "4e646029-e817-4968-a19e-d590ef10cd50",
                            CreateTime = new DateTime(2024, 7, 22, 22, 24, 4, 933, DateTimeKind.Local).AddTicks(8710),
                            Email = "yayirgul@gmail.com",
                            EmailConfirmed = true,
                            Firstname = "Yunus",
                            IsActive = false,
                            Lastname = "AYIRGÜL",
                            LockoutEnabled = false,
                            NormalizedEmail = "YAYIRGUL@GMAIL.COM",
                            NormalizedUserName = "YAYIRGUL@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMzaMuGikYAJHGYw31MbIF1mOrzBl6BNZVGy2JnuPlnEh+cWBlofmYh8imABWIh8tA==",
                            PhoneNumber = "+905558008040",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a8a7e896-7ff2-49ff-bc6d-c9feca75755c",
                            TwoFactorEnabled = false,
                            UserName = "yayirgul@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("89da7c75-8291-4baf-9060-028a07393dde"),
                            AccessFailedCount = 0,
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ConcurrencyStamp = "699e94f0-e53d-41f5-87a9-f2290d04380e",
                            CreateTime = new DateTime(2024, 7, 22, 22, 24, 4, 969, DateTimeKind.Local).AddTicks(850),
                            Email = "kadirkeles@hotmail.com",
                            EmailConfirmed = true,
                            Firstname = "Kadir",
                            IsActive = false,
                            Lastname = "Keleş",
                            LockoutEnabled = false,
                            NormalizedEmail = "KADIRKELES@HOTMAIL.COM",
                            NormalizedUserName = "KADIRKELES@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIvNyFcME1MIEqX8QSw5jmCxrrFbobawuCTj1tzCNOBpKyAJHSP5Yyu17bgAR7FEKg==",
                            PhoneNumber = "+905558008050",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "54c5a647-a7c2-4861-8fa3-1a51c06360a2",
                            TwoFactorEnabled = false,
                            UserName = "kadirkeles@hotmail.com"
                        },
                        new
                        {
                            Id = new Guid("a35a610d-689f-4ab4-9324-cc227bfdbfba"),
                            AccessFailedCount = 0,
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ConcurrencyStamp = "7be15d97-b3d5-4c1a-a152-d3ef399d4fc8",
                            CreateTime = new DateTime(2024, 7, 22, 22, 24, 5, 5, DateTimeKind.Local).AddTicks(5441),
                            Email = "lokmanyilmaz@hotmail.com",
                            EmailConfirmed = true,
                            Firstname = "Lokman",
                            IsActive = false,
                            Lastname = "Yılmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "LOKMANYILMAZ@HOTMAIL.COM",
                            NormalizedUserName = "LOKMANYILMAZ@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG5dv7FtraANsNsM6TvDkGYQ8lOBE8T+kvlMf2QHey8fI69tkTLNeyt5UB7GfO586Q==",
                            PhoneNumber = "+905558008060",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "891bded2-1430-4bb5-9637-235f796c5c87",
                            TwoFactorEnabled = false,
                            UserName = "lokmanyilmaz@hotmail.com"
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            RoleId = new Guid("4271dd20-390a-46ce-b67d-59678a720270")
                        },
                        new
                        {
                            UserId = new Guid("89da7c75-8291-4baf-9060-028a07393dde"),
                            RoleId = new Guid("4438dff4-28d6-46c1-90eb-f6b2a233d97e")
                        },
                        new
                        {
                            UserId = new Guid("a35a610d-689f-4ab4-9324-cc227bfdbfba"),
                            RoleId = new Guid("051004f1-a383-4746-a722-3b051d12aaea")
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ams.entity.Entities.Debit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DebitUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HousingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DebitUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("HousingId");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("Debits");
                });

            modelBuilder.Entity("ams.entity.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<Guid?>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenseName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ams.entity.Entities.Housing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HousingName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("HousingSafe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HousingUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("HousingSafe")
                        .IsUnique()
                        .HasFilter("[HousingSafe] IS NOT NULL");

                    b.HasIndex("HousingUser");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("Housings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("709a770b-66c6-4adc-bd19-6438117bf646"),
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ApartmentId = new Guid("d4033eef-ba92-4a1f-9ecb-1eee6996214a"),
                            CreateTime = new DateTime(2024, 7, 22, 22, 24, 5, 42, DateTimeKind.Local).AddTicks(6216),
                            CreateUser = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            HousingName = "Daire 1",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.HousingSafe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HousingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HousingSafeUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("HousingSafeUser");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("HousingSafes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("666776f7-518b-4805-a726-eba238e03fc4"),
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            Amount = 100m,
                            ApartmentId = new Guid("d4033eef-ba92-4a1f-9ecb-1eee6996214a"),
                            CreateTime = new DateTime(2024, 7, 22, 22, 24, 5, 42, DateTimeKind.Local).AddTicks(6799),
                            HousingId = new Guid("709a770b-66c6-4adc-bd19-6438117bf646"),
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.Account", b =>
                {
                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.Apartment", b =>
                {
                    b.HasOne("ams.entity.Entities.Account", "Accounts")
                        .WithMany("Apartments")
                        .HasForeignKey("AccountId");

                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("Accounts");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.AppRoleClaim", b =>
                {
                    b.HasOne("ams.entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ams.entity.Entities.AppUser", b =>
                {
                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserClaim", b =>
                {
                    b.HasOne("ams.entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserLogin", b =>
                {
                    b.HasOne("ams.entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserRole", b =>
                {
                    b.HasOne("ams.entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserToken", b =>
                {
                    b.HasOne("ams.entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ams.entity.Entities.Debit", b =>
                {
                    b.HasOne("ams.entity.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DebitTheUser")
                        .WithMany()
                        .HasForeignKey("DebitUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.Housing", "Housing")
                        .WithMany("Debits")
                        .HasForeignKey("HousingId");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("Account");

                    b.Navigation("Apartment");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DebitTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("Housing");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.Expense", b =>
                {
                    b.HasOne("ams.entity.Entities.Account", "Accounts")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.Apartment", "Apartments")
                        .WithMany()
                        .HasForeignKey("ApartmentId");

                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.Housing", b =>
                {
                    b.HasOne("ams.entity.Entities.Account", "Account")
                        .WithMany("Housings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId");

                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.HousingSafe", "HousingTheSafe")
                        .WithOne("Housing")
                        .HasForeignKey("ams.entity.Entities.Housing", "HousingSafe");

                    b.HasOne("ams.entity.Entities.AppUser", "HousingTheUser")
                        .WithMany()
                        .HasForeignKey("HousingUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("Account");

                    b.Navigation("Apartment");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("HousingTheSafe");

                    b.Navigation("HousingTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.HousingSafe", b =>
                {
                    b.HasOne("ams.entity.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.AppUser", "HousingSafeTheUser")
                        .WithMany()
                        .HasForeignKey("HousingSafeUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("Account");

                    b.Navigation("Apartment");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("HousingSafeTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.Account", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Housings");
                });

            modelBuilder.Entity("ams.entity.Entities.Housing", b =>
                {
                    b.Navigation("Debits");
                });

            modelBuilder.Entity("ams.entity.Entities.HousingSafe", b =>
                {
                    b.Navigation("Housing");
                });
#pragma warning restore 612, 618
        }
    }
}
