// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ams.data.Context;

#nullable disable

namespace ams.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240722173742_ams_v1")]
    partial class ams_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ams.entity.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("bit");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            AccountName = "ABC A.Ş",
                            CreateTime = new DateTime(2024, 7, 22, 20, 37, 42, 511, DateTimeKind.Local).AddTicks(5054),
                            CreateUser = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            Domain = "abc.com",
                            IsActive = true,
                            IsDeleted = false,
                            IsTrial = true
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.AdxMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icons")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Urls")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AdxMenus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2b3d904-401c-431f-9845-7fa2652d87fc"),
                            CreateTime = new DateTime(2024, 7, 22, 20, 37, 42, 511, DateTimeKind.Local).AddTicks(5788),
                            IsActive = true,
                            IsDeleted = false,
                            ParentId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Pano",
                            Urls = "/"
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4033eef-ba92-4a1f-9ecb-1eee6996214a"),
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ApartmentName = "Huzur APT",
                            CreateTime = new DateTime(2024, 7, 22, 20, 37, 42, 511, DateTimeKind.Local).AddTicks(6277),
                            CreateUser = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("16f885ff-6897-4d08-afa6-0640c40d2a05"),
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ApartmentName = "Sevinç APT",
                            CreateTime = new DateTime(2024, 7, 22, 20, 37, 42, 511, DateTimeKind.Local).AddTicks(6284),
                            CreateUser = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("d2977402-d13f-423f-bc0f-e639e4a610bb"),
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ApartmentName = "Güvenç APT",
                            CreateTime = new DateTime(2024, 7, 22, 20, 37, 42, 511, DateTimeKind.Local).AddTicks(6286),
                            CreateUser = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4271dd20-390a-46ce-b67d-59678a720270"),
                            ConcurrencyStamp = "6119d03b-7930-4955-a28e-e95ec04f322b",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("4438dff4-28d6-46c1-90eb-f6b2a233d97e"),
                            ConcurrencyStamp = "e8dc9981-052c-41a6-99c6-0dac40c332bd",
                            Name = "agent",
                            NormalizedName = "AGENT"
                        },
                        new
                        {
                            Id = new Guid("051004f1-a383-4746-a722-3b051d12aaea"),
                            ConcurrencyStamp = "b90e39b6-ec70-4260-8c58-062b42cbe2f3",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("ams.entity.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("ModifiedUser");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            AccessFailedCount = 0,
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ConcurrencyStamp = "03737677-1e84-46f7-bf3d-b81e814f87e3",
                            CreateTime = new DateTime(2024, 7, 22, 20, 37, 42, 513, DateTimeKind.Local).AddTicks(128),
                            Email = "yayirgul@gmail.com",
                            EmailConfirmed = true,
                            Firstname = "Yunus",
                            IsActive = false,
                            Lastname = "AYIRGÜL",
                            LockoutEnabled = false,
                            NormalizedEmail = "YAYIRGUL@GMAIL.COM",
                            NormalizedUserName = "YAYIRGUL@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECIbEvh5gayGROfahGNm7apM2z1vs+70wIHtaraiddi/zyOVXt9AcmcnoyG2Lz45GA==",
                            PhoneNumber = "+905558008040",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "93193a71-fe69-433c-87be-03734265e798",
                            TwoFactorEnabled = false,
                            UserName = "yayirgul@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("89da7c75-8291-4baf-9060-028a07393dde"),
                            AccessFailedCount = 0,
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ConcurrencyStamp = "6b9fad65-b603-4613-8677-0939b0c0beb7",
                            CreateTime = new DateTime(2024, 7, 22, 20, 37, 42, 549, DateTimeKind.Local).AddTicks(1369),
                            Email = "kadirkeles@hotmail.com",
                            EmailConfirmed = true,
                            Firstname = "Kadir",
                            IsActive = false,
                            Lastname = "Keleş",
                            LockoutEnabled = false,
                            NormalizedEmail = "KADIRKELES@HOTMAIL.COM",
                            NormalizedUserName = "KADIRKELES@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGpXI6qerECfc5VVgs4Zu//uRwnBph8u1AtiP5ZVnUMBIMFLex0LK3WY1a3MYgfacA==",
                            PhoneNumber = "+905558008050",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "cdcb6781-65d0-4bc4-99c0-458fd5469451",
                            TwoFactorEnabled = false,
                            UserName = "kadirkeles@hotmail.com"
                        },
                        new
                        {
                            Id = new Guid("a35a610d-689f-4ab4-9324-cc227bfdbfba"),
                            AccessFailedCount = 0,
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ConcurrencyStamp = "5b068333-3255-4914-9049-02e6a9fd7f5f",
                            CreateTime = new DateTime(2024, 7, 22, 20, 37, 42, 585, DateTimeKind.Local).AddTicks(289),
                            Email = "lokmanyilmaz@hotmail.com",
                            EmailConfirmed = true,
                            Firstname = "Lokman",
                            IsActive = false,
                            Lastname = "Yılmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "LOKMANYILMAZ@HOTMAIL.COM",
                            NormalizedUserName = "LOKMANYILMAZ@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIaod5oZe7y0mM8/gDsKCfs0XZCZKUkeKwmTBpDHDea7hUH1m23y4KkFKsTyPDq5Jw==",
                            PhoneNumber = "+905558008060",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "69a73d0f-1fb7-48ff-85b1-d1fdc44cf70e",
                            TwoFactorEnabled = false,
                            UserName = "lokmanyilmaz@hotmail.com"
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6fa95f6e-2516-49e8-9ae6-7745e7743dbf"),
                            RoleId = new Guid("4271dd20-390a-46ce-b67d-59678a720270")
                        },
                        new
                        {
                            UserId = new Guid("89da7c75-8291-4baf-9060-028a07393dde"),
                            RoleId = new Guid("4438dff4-28d6-46c1-90eb-f6b2a233d97e")
                        },
                        new
                        {
                            UserId = new Guid("a35a610d-689f-4ab4-9324-cc227bfdbfba"),
                            RoleId = new Guid("051004f1-a383-4746-a722-3b051d12aaea")
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ams.entity.Entities.Debit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DebitUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HousingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DebitUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("HousingId");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("Debits");
                });

            modelBuilder.Entity("ams.entity.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<Guid?>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenseName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ams.entity.Entities.Housing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HousingName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("HousingUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("HousingUser");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("Housings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("709a770b-66c6-4adc-bd19-6438117bf646"),
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            ApartmentId = new Guid("d4033eef-ba92-4a1f-9ecb-1eee6996214a"),
                            CreateTime = new DateTime(2024, 7, 22, 20, 37, 42, 623, DateTimeKind.Local).AddTicks(3175),
                            HousingName = "Daire 1",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.HousingSafe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HousingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HousingSafeUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IsStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreateUser");

                    b.HasIndex("DeleteUser");

                    b.HasIndex("HousingId");

                    b.HasIndex("HousingSafeUser");

                    b.HasIndex("ModifiedUser");

                    b.ToTable("HousingSafes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("666776f7-518b-4805-a726-eba238e03fc4"),
                            AccountId = new Guid("db72e0e2-3201-414f-9753-190466e024f3"),
                            Amount = 100m,
                            ApartmentId = new Guid("d4033eef-ba92-4a1f-9ecb-1eee6996214a"),
                            CreateTime = new DateTime(2024, 7, 22, 20, 37, 42, 623, DateTimeKind.Local).AddTicks(4311),
                            HousingId = new Guid("709a770b-66c6-4adc-bd19-6438117bf646"),
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ams.entity.Entities.Account", b =>
                {
                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.Apartment", b =>
                {
                    b.HasOne("ams.entity.Entities.Account", "Accounts")
                        .WithMany("Apartments")
                        .HasForeignKey("AccountId");

                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("Accounts");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.AppRoleClaim", b =>
                {
                    b.HasOne("ams.entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ams.entity.Entities.AppUser", b =>
                {
                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserClaim", b =>
                {
                    b.HasOne("ams.entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserLogin", b =>
                {
                    b.HasOne("ams.entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserRole", b =>
                {
                    b.HasOne("ams.entity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ams.entity.Entities.AppUserToken", b =>
                {
                    b.HasOne("ams.entity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ams.entity.Entities.Debit", b =>
                {
                    b.HasOne("ams.entity.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DebitTheUser")
                        .WithMany()
                        .HasForeignKey("DebitUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.Housing", "Housing")
                        .WithMany("Debits")
                        .HasForeignKey("HousingId");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("Account");

                    b.Navigation("Apartment");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DebitTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("Housing");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.Expense", b =>
                {
                    b.HasOne("ams.entity.Entities.Account", "Accounts")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.Apartment", "Apartments")
                        .WithMany()
                        .HasForeignKey("ApartmentId");

                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("Accounts");

                    b.Navigation("Apartments");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.Housing", b =>
                {
                    b.HasOne("ams.entity.Entities.Account", "Account")
                        .WithMany("Housings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId");

                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.AppUser", "HousingTheUser")
                        .WithMany()
                        .HasForeignKey("HousingUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("Account");

                    b.Navigation("Apartment");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("HousingTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.HousingSafe", b =>
                {
                    b.HasOne("ams.entity.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ams.entity.Entities.AppUser", "CreateTheUser")
                        .WithMany()
                        .HasForeignKey("CreateUser");

                    b.HasOne("ams.entity.Entities.AppUser", "DeleteTheUser")
                        .WithMany()
                        .HasForeignKey("DeleteUser");

                    b.HasOne("ams.entity.Entities.Housing", "Housing")
                        .WithMany()
                        .HasForeignKey("HousingId");

                    b.HasOne("ams.entity.Entities.AppUser", "HousingSafeTheUser")
                        .WithMany()
                        .HasForeignKey("HousingSafeUser");

                    b.HasOne("ams.entity.Entities.AppUser", "ModifiedTheUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUser");

                    b.Navigation("Account");

                    b.Navigation("Apartment");

                    b.Navigation("CreateTheUser");

                    b.Navigation("DeleteTheUser");

                    b.Navigation("Housing");

                    b.Navigation("HousingSafeTheUser");

                    b.Navigation("ModifiedTheUser");
                });

            modelBuilder.Entity("ams.entity.Entities.Account", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Housings");
                });

            modelBuilder.Entity("ams.entity.Entities.Housing", b =>
                {
                    b.Navigation("Debits");
                });
#pragma warning restore 612, 618
        }
    }
}
